#!/bin/bash

export PATH=$PATH:/home/andrew/altera/13.1/modelsim_ase/bin

HNOCSIM_DIR='/home/andrew/Dropbox/MASc/hnocsim'
DESIGN_DIR=$HNOCSIM_DIR/designs/switch_fabric

#remake booksim
cd $HNOCSIM_DIR/booksim
make
cd $DESIGN_DIR

#create work library
rm -rf work
vlib work

#######################
#compile verilog files
#######################

#compile the rtl interface that talks to booksim's socket interface
vlog -dpiheader $HNOCSIM_DIR/booksim/dpi.h $HNOCSIM_DIR/booksim/rtl_interface.sv

#compile the fabric port
vlog  $HNOCSIM_DIR/fabric_port/fabric_port_in/*.sv
vlog  $HNOCSIM_DIR/fabric_port/fabric_port_out/*.sv

#compile the fabric interface which instantiates fabric ports and an rtl interface
vlog $HNOCSIM_DIR/booksim/fabric_interface.sv

#compile your design files (and testbenches) here
vlog avalon_eth_source_sink.sv
vlog testbench.sv
vlog ibuffer.sv
vlog obuffer.sv
vlog top.sv
vlog fifo_emptyw.v
vlog fifo_shallow_almf.v
vlog switch_packetizer.sv
vlog switch_depacketizer.sv

#########################################
#recompile the booksim socket interface
########################################

g++ -c -fPIC -m32 -I/home/andrew/altera/13.1/modelsim_ase/include $HNOCSIM_DIR/booksim/booksim_interface.cpp
g++ -shared -Bsymbolic -fPIC -m32 -o booksim_interface.so booksim_interface.o

###############################
#run booksim in a new terminal
###############################

if [ "$1" == "keep_open" ]; then
	gnome-terminal --window-with-profile=keep_open -e $HNOCSIM_DIR/booksim/booksim\ noc_config &
else
	gnome-terminal -e $HNOCSIM_DIR/booksim/booksim\ noc_config &
fi

################
#run simulation
################

if [ "$1" == "vsim" ]; then
	vsim -L /home/andrew/altera/13.1/modelsim_ase/altera/verilog/altera_mf -sv_lib booksim_interface testbench -do wave1.do 
else
	vsim -L /home/andrew/altera/13.1/modelsim_ase/altera/verilog/altera_mf -c -sv_lib booksim_interface testbench -do "run -all"
fi

#########
#cleanup
#########

killall booksim
killall vsimk
killall vsim
killall vish

rm -r work
rm transcript
rm socket
rm *.out
rm *.o *.so *.wlf *.vstf
