#!/bin/bash

export PATH=$PATH:/home/andrew/altera/13.1/modelsim_ase/bin

HNOCSIM_DIR='/home/andrew/Dropbox/MASc/hnocsim'
DESIGN_DIR=$HNOCSIM_DIR/designs/pkt_parser

#remake booksim
cd $HNOCSIM_DIR/booksim
make
cd $DESIGN_DIR

rm -rf work
vlib work

#compile the rtl interface that talks to booksim's socket interface
vlog -dpiheader $HNOCSIM_DIR/booksim/dpi.h $HNOCSIM_DIR/booksim/rtl_interface.sv

#compile the fabric port
vlog  $HNOCSIM_DIR/fabric_port/fabric_port_in/*.sv
vlog  $HNOCSIM_DIR/fabric_port/fabric_port_out/*.sv

#compile the fabric interface which instantiates fabric ports and an rtl interface
vlog $HNOCSIM_DIR/booksim/fabric_interface.sv

#compile the sw fabric interface
vlog -dpiheader $HNOCSIM_DIR/booksim/dpi_fabric.h $HNOCSIM_DIR/booksim/fabric_interface_sw.sv

#compile ddr design
#vlog ../ddr3/simple_frame_buffer/*.sv
#vlog ../ddr3/simple_frame_buffer_noc/*.sv

#compile verilog files
vlog global_package.sv
vlog pcapreader512.sv
vlog fifo_emptyw.v
vlog fifo_emptyw_auto.v
vlog avalon_st_interface.sv
vlog pre_process.sv
vlog ram.v
vlog ethernet512.sv
vlog translator_in.sv
vlog translator_out.sv
vlog ipv4_512.sv
vlog ipv4_top.sv
vlog ipv6_512.sv
vlog ipv6_top.sv
vlog arbiter2to1.sv
vlog ipv4_ipv6_top.sv
vlog tcp512.sv
vlog tcp_top.sv
vlog txr_to_noc_basic.sv
vlog noc_to_txr_basic.sv
vlog noc_to_tcp_to_txr.sv
vlog monitor.sv
vlog testbench_basic_full.sv


#########################################
#recompile the booksim socket interface
########################################

g++ -c -fPIC -m32 -I/home/andrew/altera/13.1/modelsim_ase/include $HNOCSIM_DIR/booksim/booksim_interface.cpp
g++ -shared -Bsymbolic -fPIC -m32 -o booksim_interface.so booksim_interface.o

g++ -c -fPIC -m32 -I$HNOCSIM_DIR/booksim -I/home/mohamed/altera/14.0/modelsim_ase/include $HNOCSIM_DIR/booksim/fabric_sw_interface.cpp
g++ -shared -Bsymbolic -fPIC -m32 -o fabric_sw_interface.so fabric_sw_interface.o

