/* MTI_DPI */

/*
 * Copyright 2002-2013 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linuxpe'
 */
#ifndef INCLUDED_DPI_FABRIC
#define INCLUDED_DPI_FABRIC

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
checkNocReady(
    int node,
    int vc);

DPI_LINK_DECL DPI_DLLESPEC
void
connectFabricSocket();

DPI_LINK_DECL DPI_DLLESPEC
void
ejectFourFabric(
    int node,
    int* id0,
    int* id1,
    int* id2,
    int* id3,
    int* valid);

DPI_LINK_DECL DPI_DLLESPEC
void
exitFabricSocket();

DPI_LINK_DECL DPI_DLLESPEC
void
nextFabricCycle(
    int speedup);

DPI_LINK_DECL DPI_DLLESPEC
void
queueFabricFlit(
    int pid,
    int fid,
    int source,
    int destination,
    int vc,
    int head,
    int tail);

DPI_LINK_DECL DPI_DLLESPEC
void
sendModuleReady(
    int node,
    int vc,
    int ready);

#endif 
