#!/bin/bash

export PATH=$PATH:/home/mohamed/altera/14.0/modelsim_ase/bin

HNOCSIM_DIR='/home/mohamed/Dropbox/PhD/Software/simulator/hnocsim'
DESIGN_DIR=$HNOCSIM_DIR/designs/fabricport_sw

#remake booksim
cd $HNOCSIM_DIR/booksim
make
cd $DESIGN_DIR

#create work library
rm -rf work
vlib work

#######################
#compile verilog files
#######################

#compile the rtl interface that talks to booksim's socket interface
vlog -dpiheader $HNOCSIM_DIR/booksim/dpi.h $HNOCSIM_DIR/booksim/rtl_interface.sv

#compile the fabric port
vlog  $HNOCSIM_DIR/fabric_port/fabric_port_in/*.sv
vlog  $HNOCSIM_DIR/fabric_port/fabric_port_out/*.sv

#replace depacketizer with one that extracts valid
vlog  depacketizer.sv

#compile the fabric interface which instantiates fabric ports and an rtl interface
vlog $HNOCSIM_DIR/booksim/fabric_interface.sv

#compile the sw fabric interface
vlog -dpiheader $HNOCSIM_DIR/booksim/dpi_fabric.h $HNOCSIM_DIR/booksim/fabric_interface_sw.sv

#compile your design files (and testbenches) here
vlog testbench_simple_fabric.sv

#########################################
#recompile the booksim socket interface
########################################

g++ -c -fPIC -m32 -I$HNOCSIM_DIR/booksim -I/home/mohamed/altera/14.0/modelsim_ase/include $HNOCSIM_DIR/booksim/fabric_sw_interface.cpp
g++ -shared -Bsymbolic -fPIC -m32 -o fabric_sw_interface.so fabric_sw_interface.o

###############################
#run booksim in a new terminal
###############################

if [ "$1" == "keep_open" ]; then
	gnome-terminal --window-with-profile=keep_open -e $HNOCSIM_DIR/booksim/booksim\ noc_config &
else
	gnome-terminal -e $HNOCSIM_DIR/booksim/booksim\ noc_config &
fi

################
#run simulation
################

if [ "$1" == "vsim" ]; then
	vsim -sv_lib fabric_sw_interface testbench -do wave.do 
else
	vsim -c -sv_lib fabric_sw_interface testbench -do "run -all"
fi

#########
#cleanup
#########

killall booksim
killall vsim
killall vsimk

rm -r work
rm transcript
rm socket
rm *.out
rm *.o *.so *.wlf *.vstf
